name: Build Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Submodules
      uses: actions/checkout@v4
    - name: Install PHP
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "latest"
    - name: "Install NPM"
      run : sudo npm install --unsafe-perm=true --allow-root
    - name: Install Composer Dependencies
      uses: php-actions/composer@v6
      with:
        php_version: "latest"
        command: install --no-progress --no-dev --optimize-autoloader
    - name: Remove Submodules
      run: |   
        git rm -r -f .gitmodules
        git submodule update --init
        git rm -r -f --cached src/um-wpcli
        rm -rf .git/modules/src/um-wpcli
    - name: Add UM-WPCLI
      run: | 
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git rm .gitignore
          rm -rf src/um-wpcli
          git clone https://github.com/ultimatemember/um-wpcli.git src/um-wpcli
          rm -rf src/um-wpcli/.git/
          git add src/um-wpcli/*
          git commit -a -m "Added UM-WPCLI"
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add vendor/*
        git rm -r docs
        git commit -a -m "Composer Installed"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.UM_EXTENDED_ACTION_SECRET }}
        branch: releases
        repository: ultimatemember/Extended
        force: true
